name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  release:
      types: [published]
env:
#edit your values here
  ENVIRONMENT_URL: 'https://org3c975e83.crm7.dynamics.com'
  CLIENT_ID: 'e780b8b2-eb83-4a9b-a45f-1526ef9b2c34'
  TENANT_ID: 'e0cd32dc-b9c0-48dd-82e4-98f2490b4655'
  SOLUTION_NAME: 'ALMLab'
  SOLUTION_EXPORTED_FOLDER: 'out/exported/'
  SOLUTION_FOLDER: 'out/solutions/'
  SOLUTION_TARGET_FOLDER: 'solutions/'
  SOLUTION_SOURCE_FOLDER: 'solutions/'
  SOLUTION_OUTBOUND_FOLDER: 'out/solutions/'
  SOLUTION_SHIPPING_FOLDER: 'out/ship'
  SOLUTION_RELEASE_FOLDER: 'out/ship'

jobs:
  export-from-dev:
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}


    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{env.SOLUTION_NAME}}
        solution-output-file: ${{env.SOLUTION_EXPORTED_FOLDER}}/${{env.SOLUTION_NAME}}.zip

    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v0
      with:
        solution-file: ${{env.SOLUTION_EXPORTED_FOLDER}}/${{env.SOLUTION_NAME}}.zip
        solution-folder: ${{env.SOLUTION_FOLDER}}/${{env.SOLUTION_NAME}}
        solution-type: 'Unmanaged'
        overwrite-files: true

    - name: branch-solution, prepare it for a PullRequest
      uses: microsoft/powerplatform-actions/branch-solution@v0
      with:
        solution-folder: ${{env.SOLUTION_FOLDER}}/${{env.SOLUTION_NAME}}
        solution-target-folder: ${{env.SOLUTION_TARGET_FOLDER}}/${{env.SOLUTION_NAME}}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        allow-empty-commit: true

  convert-to-managed:
    needs: export-from-dev
    runs-on: windows-latest
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Pack solution
      uses: microsoft/powerplatform-actions/pack-solution@v0
      with:
        solution-folder: ${{env.SOLUTION_SOURCE_FOLDER}}/${{env.SOLUTION_NAME}}
        solution-file: ${{env.SOLUTION_OUTBOUND_FOLDER}}/${{env.SOLUTION_NAME}}.zip
        solution-type: Unmanaged

    - name: Import solution as unmanaged to build env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{env.SOLUTION_OUTBOUND_FOLDER}}/${{env.SOLUTION_NAME}}.zip
        force-overwrite: true
        publish-changes: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{env.SOLUTION_NAME}}
        managed: true
        solution-output-file: ${{env.SOLUTION_SHIPPING_FOLDER}}/${{env.SOLUTION_NAME}}.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: ${{env.SOLUTION_SHIPPING_FOLDER}}/

  release-to-staging:
    needs: convert-to-managed
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: ${{env.SOLUTION_RELEASE_FOLDER}}
    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@v0
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{env.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: ${{env.SOLUTION_RELEASE_FOLDER}}/${{env.SOLUTION_NAME}}.zip
        force-overwrite: true
        publish-changes: true